name: Compile luci-app-ssr-plus PKG ONLY

on:
  push:
    branches: 
      - ssr-plus-pkg
  schedule:
    - cron: 0 */3 * * * 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: 'ssr-plus-pkg'
        fetch-depth: '1'

    - name: Call Compile Script
      env:
        DEBIAN_FRONTEND: noninteractive
      run: /bin/bash scripts/compile_ssr-plus-pkg.sh
